### ISSUE TITLE
Non-critical issues

### ISSUE THREAD

**Issue by encukou** [pyvec/naucse-hooks#1]
- [x] `get_latest_naucse` deletes the whole local repository if a pull doesn't suceed. Should it rather do fetch and reset? That functionality could be useful enough to be in Arca. 
- [x] Most of `_iterate` can be replaced with [`Path.glob('**/link.yml')`](https://docs.python.org/3.5/library/pathlib.html#pathlib.Path.glob)

**Comment by mikicz** [comment]
2d145632d91a4044e6f007c1d9a8fd0673681f64 and d8c58faf2b1a394f8990174e789e409f88fe99f4
